language: java

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - wget "https://my.owndrive.com/public.php?service=files&t=d238bd41ebef0e377a81781cf7bb56f1&download" -O android.tgz
  - tar -zxf android.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-light
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
